export const BALLOONS = [
  
  { id: "o1", img: require("../assets/balloons/fruits/o1.png") },
  { id: "o2", img: require("../assets/balloons/fruits/o2.png") },
  { id: "o3", img: require("../assets/balloons/fruits/o3.png") },
  { id: "o4", img: require("../assets/balloons/fruits/o4.png") },
  { id: "o5", img: require("../assets/balloons/fruits/o5.png") },
  
  { id: "s1", img: require("../assets/balloons/sweets/s1.png") },
  { id: "s2", img: require("../assets/balloons/sweets/s2.png") },
  { id: "s3", img: require("../assets/balloons/sweets/s3.png") },
  { id: "s4", img: require("../assets/balloons/sweets/s4.png") },
  { id: "s5", img: require("../assets/balloons/sweets/s5.png") },
  { id: "s6", img: require("../assets/balloons/sweets/s6.png") },
  { id: "s7", img: require("../assets/balloons/sweets/s7.png") },


  { id: "z1", img: require("../assets/balloons/animals/z1.png") },
  { id: "z2", img: require("../assets/balloons/animals/z2.png") },
  { id: "z3", img: require("../assets/balloons/animals/z3.png") },
  { id: "z4", img: require("../assets/balloons/animals/z4.png") },
  { id: "z5", img: require("../assets/balloons/animals/z5.png") },
  { id: "z6", img: require("../assets/balloons/animals/z6.png") },
  { id: "z7", img: require("../assets/balloons/animals/z7.png") },
  { id: "z8", img: require("../assets/balloons/animals/z8.png") },
  { id: "z9", img: require("../assets/balloons/animals/z9.png") },
  { id: "z10", img: require("../assets/balloons/animals/z10.png") },
  { id: "z11", img: require("../assets/balloons/animals/z11.png") },
  { id: "z12", img: require("../assets/balloons/animals/z12.png") },
  { id: "z13", img: require("../assets/balloons/animals/z13.png") },
  { id: "z14", img: require("../assets/balloons/animals/z14.png") },
  { id: "z15", img: require("../assets/balloons/animals/z15.png") },
  { id: "z16", img: require("../assets/balloons/animals/z16.png") },
  { id: "z17", img: require("../assets/balloons/animals/z17.png") },
  { id: "z18", img: require("../assets/balloons/animals/z18.png") },
  { id: "z19", img: require("../assets/balloons/animals/z19.png") },
  { id: "z20", img: require("../assets/balloons/animals/z20.png") },
  { id: "z21", img: require("../assets/balloons/animals/z21.png") },
  { id: "z22", img: require("../assets/balloons/animals/z22.png") },
  { id: "z23", img: require("../assets/balloons/animals/z23.png") },
  { id: "z24", img: require("../assets/balloons/animals/z24.png") },
  { id: "z25", img: require("../assets/balloons/animals/z25.png") },
  { id: "z26", img: require("../assets/balloons/animals/z26.png") },
  { id: "z27", img: require("../assets/balloons/animals/z27.png") },
  { id: "z28", img: require("../assets/balloons/animals/z28.png") },
  { id: "z29", img: require("../assets/balloons/animals/z29.png") },
] as const;

export type Balloon = (typeof BALLOONS)[number];
